### ISSUE TITLE
Honeypot deleted unexpectedly

### ISSUE THREAD

**Issue by siyukatu** [TerrorByteTW/Honeypot#126]
**Describe the bug**
When holding the sword in creative mode and clicking on the honeypot, the "Destroyed" message appears even though it has not been destroyed.
Then the block remains there and the honeypot is removed.

**To Reproduce**
1. /gamemode creative
2. Hold sword
3. Click the honeypot
4. Honeypot removed

**Expected behavior**
Nothing happens

**Version Info (please complete the following information):**
 - Honeypot Version: 2.6.1
 - Java Version: IDK
 - MC Server Version: 1.19.3
 - MC Server Type: Paper

**Comment by siyukatu** [comment]
I have Op permission

**Comment by TerrrorByte** [comment]
Issue identified. Creative players with swords in hand will still call Spigot's BlockBreakEvent but it will be cancelled by default. Checking if the event is cancelled before further processing helps. Will release fix within the hour.
